### ISSUE TITLE
Core appears to freeze waiting for GazePoint to connect

### ISSUE THREAD

**Issue by fisherdog1** [iTrace-Dev/iTrace-Core#177]
Freezes on splash screen, only observed on SmartEye laptop for now. Check to see if freeze also happens on Tobii station?

**Comment by samuel0correia** [comment]
Hello, I believe I am facing a similar problem. I suspect that the fix you mention was implemented for release 0.2.0 but I am still freezing when launching iTrace core with the console only presenting: 
"Gaze Point not connected!
Attempting to connect to Smarteye..."

Previously I was able to launch the app but now I am not and I am not sure what changed.

**Comment by samuel0correia** [comment]
The attached image is what currently happens when I launch iTrace Core. This happens with or without Gazepoint Control running and with or without having the eye tracker plugged in. I have also tried reinstalling iTrace Core to no avail.

<img width="733" alt="image" src="https://github.com/iTrace-Dev/iTrace-Core/assets/73120690/6035ff13-0ad5-4814-87c6-eefd5cd811d5">

This is with iTrace Core 0.2.0 on Windows 11 (21H2)

**Comment by samuel0correia** [comment]
I believe that I have determined what was causing my specific issue.
I had recently installed Couldflare WARP. When this application is connected the program fails to load, as soon as it is disconnected it starts working again.

This might also occur with other applications such as VPNs but I am currently unable to check.

**Comment by shbonita** [comment]
Thanks for reporting back @wildpiggie I am glad that it is now working.
