### ISSUE TITLE
Error when saving settings

### ISSUE THREAD

**Issue by KangilPark** [iTrace-Dev/iTrace-Core#186]
While trying to change the calibration_monitor setting, I found that when clicking "Apply" in the settings tab, Core will give the error, "Port values must be numeric!":

![iTrace Core Settings Issue](https://user-images.githubusercontent.com/15721187/236933063-95340c38-946b-4428-a74f-ee49616688ed.PNG)

Current workaround to change recording monitor is to edit the iTrace-Core.exe.config file directly that is in Core's directory (calibration_monitor = 0 for primary monitor, 1 for external monitor).

**Comment by KangilPark** [comment]
After further testing, it appears that the error message appears whether or not any of the values in the _Settings_ tab were changed.

**Comment by toBeOfUse** [comment]
In case no one has looked into this yet, the immediate problem is here:

https://github.com/iTrace-Dev/iTrace-Core/blob/36b13f033133735c2b8001cc0a9471d4b4396c3c/itrace_core/MainWindow.xaml.cs#L118-L123

The `ApplySettings` function is out of date with the `settings` variable. At the end of line 123, `settings[2]` is parsed as an int when that index actually stores an IP address; it should be changed to `settings[4]`. Similarly, on line 155, `settings[4]` should be used, or the existing `calibrationMonitor` variable could be.

Also, that function should probably return after displaying the error message on line 150, to avoid saving or trying to save an invalid value for `Settings.Default.calibration_monitor`. Also, plausibly, the values for the settings `smarteye_ip_address` and `smarteye_ip_port` should be checked for validity (the IP address must follow the right format, the port should be in the right range and not be equal to either of the other two ports) and saved as the others are; it appears that the new values for those just aren't touched. It also isn't immediately clear to me why the value for `calibrationMonitor` has to be greater than 0 (according to line 148) when the default is 0; the value should probably be greater than or equal to 0 and less than (not less than or equal to) the length of the array of screens, since it's used as an array index.

**Comment by michaeldejournett** [comment]
This fix work and allows setting to properly save to local app data.
